### ISSUE TITLE
array portfolio

### ISSUE THREAD

**Issue by superpikar** [Fakhri17/Web-Profil-Twig#1]
```
'class'=>[
        'button is-rounded is-danger',
        'button is-rounded is-primary',
        'button is-rounded is-link',
        'button is-rounded is-info',
      ],
```

`button is-rounded` tidak perlu ditulis di array karena ada pada tiap element array. langsung dimasukkan ke class HTMLnya saja

**Comment by Fakhri17** [comment]
![image](https://user-images.githubusercontent.com/54692387/66619251-82cde000-ec06-11e9-904f-891298067195.png)

**Comment by Fakhri17** [comment]
![image](https://user-images.githubusercontent.com/54692387/66636474-77e17280-ec3b-11e9-964a-cecffb13bc49.png)
