### ISSUE TITLE
data pada index.twig

### ISSUE THREAD

**Issue by superpikar** [Fakhri17/Web-Profil-Twig#2]
```html
<div class="content subtitle">
              Nama   <strong> Fakhri Alauddin         </strong>.
              TTL    <strong> Jombang, 31  Maret 2001 </strong>.
              Umur   <strong> 18 Tahun                </strong>.
              Alamat <strong> Jl.Raya Benowo No 06    </strong>.
              Hobi   <strong> Coding dan Editing      </strong>.
            </div>
```
seluruh data yang ditampilkan pada web masukkan ke array PHP, termasuk data profil jangan ditulis hardcode di `template.twig`

**Comment by Fakhri17** [comment]
### Diubah seperti ini apa mas?

![image](https://user-images.githubusercontent.com/54692387/66619130-f91e1280-ec05-11e9-9012-08d309cbf713.png)


![image](https://user-images.githubusercontent.com/54692387/66619138-03d8a780-ec06-11e9-807e-87a03b1e89e4.png)
